[package]
edition = "2018"
name = "vinyana"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "*"
rand = "*"
serde = {version = "*", features = ["derive"]}
